-- V1__create_table_medicoes_amostras.sql

CREATE TABLE PACIENTES (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_completo VARCHAR2(150 CHAR) NOT NULL,
    cpf VARCHAR2(11 CHAR) NOT NULL,
    data_nascimento DATE NOT NULL,
    genero VARCHAR2(20 CHAR) NOT NULL,
    CONSTRAINT pk_pacientes PRIMARY KEY (id)
);

ALTER TABLE PACIENTES ADD CONSTRAINT uc_pacientes_cpf UNIQUE (cpf);

CREATE TABLE MEDICOES_AMOSTRAS (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    paciente_id NUMBER(19,0) NOT NULL,
    codigo_amostra VARCHAR2(50 CHAR) NOT NULL,
    volume NUMBER(10,2) NOT NULL,
    comprimento NUMBER(10,2) NOT NULL,
    largura NUMBER(10,2) NOT NULL,
    altura NUMBER(10,2) NOT NULL,
    observacoes CLOB,
    status VARCHAR2(20 CHAR) NOT NULL,
    data_registro TIMESTAMP NOT NULL,
    CONSTRAINT pk_medicoes_amostras PRIMARY KEY (id)
);

ALTER TABLE MEDICOES_AMOSTRAS ADD CONSTRAINT uc_medicoes_amostras_codigo_amostra UNIQUE (codigo_amostra);

ALTER TABLE MEDICOES_AMOSTRAS ADD CONSTRAINT fk_medicoes_amostras_on_paciente FOREIGN KEY (paciente_id) REFERENCES PACIENTES (id);